Repository Find-A-Musician/findAMusicianBackend, pull requests merged in 2022-03, with the labels that each got.

#78 TypeORM mygration
  api/command/createEndpoint.sh
  api/command/generateType.ts
  api/command/pg_reset.sh
  api/db/config.ts
  api/db/createConnection.ts
  api/db/reset.ts
  api/docs/config/components.ts
  api/docs/config/paths.ts
  api/docs/schemas/auth/register.ts
  api/docs/schemas/events/event.ts
  api/docs/schemas/events/events.ts
  api/docs/schemas/groups/group.ts
  api/docs/schemas/groups/groups.ts
  api/docs/schemas/musicians/musicians.ts
  api/entity/Event.ts
  api/entity/Genre.ts
  api/entity/Groups.ts
  api/entity/Instrument.ts
  api/entity/Musician.ts
  api/entity/MusicianGroup.ts
  api/entity/Token.ts
  api/entity/index.ts
  api/routes/auth/login.ts
  api/routes/auth/logout.ts
  api/routes/auth/refreshToken.ts
  api/routes/auth/register.ts
  api/routes/events/events.ts
  api/routes/genres/genres.ts
  api/routes/groups/groups.ts
  api/routes/info/info.ts
  api/routes/instruments/instruments.ts
  api/routes/musicians/musicians.ts
  api/routes/profil/profil.ts
  api/server/server.ts
  api/sql/01-reset.sql
  api/sql/02-musicians.sql
  api/sql/03-genres.sql
  api/sql/04-instruments.sql
  api/sql/05-groups.sql
  api/sql/06-tokens.sql
  api/sql/07-events.sql
  api/types/doc.json
  api/types/schema.ts
  index.ts
  ormconfig.json
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement, Long issue

#89 feat(type): prettier the path.ts file for git diff
  api/command/generateType.ts
  api/docs/config/paths.ts
  index.ts
Labels: bug

#83 Add filter query for get groups
  api/docs/config/paths.ts
  api/docs/schemas/groups/groups.ts
  api/routes/groups/groups.ts
  api/routes/musicians/musicians.ts
  api/types/schema.ts
  index.ts
Labels: enhancement

#100 Update generateType to change types at first restart
  api/command/generateType.ts
  api/docs/config/index.ts
  api/docs/config/paths.ts
  api/docs/openApiDoc.ts
  api/server/server.ts
  index.ts
  nodemon.json
Labels: bug

#96 Post return an error when entity already exist
  api/docs/openApiDoc.ts
  api/docs/schemas/auth/register.ts
  api/docs/schemas/events/events.ts
  api/docs/schemas/groups/groups.ts
  api/routes/auth/register.ts
  api/routes/events/events.ts
  api/routes/groups/groups.ts
  api/types/schema.ts
Labels: bug

#103 Filter event bug
  api/routes/events/events.ts
Labels: bug

#104 Add pagination
  api/db/reset.ts
  api/docs/config/components.ts
  api/docs/openApiDoc.ts
  api/docs/schemas/events/events.ts
  api/docs/schemas/groups/groups.ts
  api/docs/schemas/musicians/musicians.ts
  api/routes/events/events.ts
  api/routes/groups/groups.ts
  api/routes/musicians/musicians.ts
  api/types/schema.ts
Labels: enhancement

#101 Return the groups of the musician
  api/docs/openApiDoc.ts
  api/docs/schemas/musicians/musician.ts
  api/docs/schemas/profil/profil.ts
  api/routes/musicians/musicians.ts
  api/routes/profil/profil.ts
  api/types/schema.ts
Labels: enhancement

#108 Musician can leave a group
  api/controllers/profil/index.ts
  api/controllers/profil/userGroup.ts
  api/docs/openApiDoc.ts
  api/docs/schemas/profil/profil.ts
  api/docs/schemas/profil/userGroup/leaveGroup.ts
  api/routes/profil/index.ts
  api/types/schema.ts
Labels: enhancement

#86 Feat: group joins event route
  api/controllers/groups/groupEvents.ts
  api/controllers/groups/index.ts
  api/docs/openApiDoc.ts
  api/docs/schemas/groups/events/groupJoinEvent.ts
  api/docs/schemas/groups/invitation/groupResponseInvitation.ts
  api/docs/schemas/groups/invitation/groupsSendInvitation.ts
  api/entity/Groups.ts
  api/routes/groups/index.ts
  api/types/schema.ts
Labels: enhancement

#121 👨‍✈️️ Add lite_admin membership
  api/controllers/groups/admin.ts
  api/controllers/groups/groups.ts
  api/controllers/groups/index.ts
  api/docs/config/components.ts
  api/docs/openApiDoc.ts
  api/docs/schemas/groups/admin/lite_admin.ts
  api/entity/MusicianGroup.ts
  api/routes/groups.ts
  api/types/schema.ts
  index.ts
Labels: enhancement

#117 🚪️ Admin kick member from group
  api/controllers/groups/index.ts
  api/controllers/groups/kick.ts
  api/docs/openApiDoc.ts
  api/docs/schemas/groups/kick.ts
  api/routes/groups.ts
  api/types/schema.ts
Labels: enhancement

#122 🔄️ Admin group membership transfer
  api/controllers/groups/admin.ts
  api/controllers/groups/index.ts
  api/docs/openApiDoc.ts
  api/docs/schemas/groups/admin/adminTransfer.ts
  api/routes/groups.ts
  api/types/schema.ts
Labels: enhancement

#124 Feat error handling
  .eslintrc.json
  .gitignore
  api/auth/authenticateToken.ts
  api/command/generateHash.ts
  api/command/generateType.ts
  api/controllers/auth/login.ts
  api/controllers/auth/logout.ts
  api/controllers/auth/refreshToken.ts
  api/controllers/auth/register.ts
  api/controllers/events/admin.ts
  api/controllers/events/events.ts
  api/controllers/events/kick.ts
  api/controllers/genres/genres.ts
  api/controllers/groups/admin.ts
  api/controllers/groups/groupEvents.ts
  api/controllers/groups/groups.ts
  api/controllers/groups/kick.ts
  api/controllers/info/info.ts
  api/controllers/instruments/instruments.ts
  api/controllers/musicians/musicians.ts
  api/controllers/profil/profil.ts
  api/controllers/profil/userGroup.ts
  api/db/createConnection.ts
  api/db/reset.ts
  api/docs/openApiDoc.ts
  api/docs/schemas/auth/login.ts
  api/docs/schemas/auth/logout.ts
  api/docs/schemas/auth/refreshToken.ts
  api/docs/schemas/auth/register.ts
  api/docs/schemas/events/admins.ts
  api/docs/schemas/events/event.ts
  api/docs/schemas/events/events.ts
  api/docs/schemas/events/kick.ts
  api/docs/schemas/genres/genres.ts
  api/docs/schemas/groups/admin/adminTransfer.ts
  api/docs/schemas/groups/admin/lite_admin.ts
  api/docs/schemas/groups/events/groupJoinEvent.ts
  api/docs/schemas/groups/group.ts
  api/docs/schemas/groups/groups.ts
  api/docs/schemas/groups/invitation/groupResponseInvitation.ts
  api/docs/schemas/groups/invitation/groupsSendInvitation.ts
  api/docs/schemas/groups/kick.ts
  api/docs/schemas/info/info.ts
  api/docs/schemas/instruments/instruments.ts
  api/docs/schemas/musicians/musician.ts
  api/docs/schemas/musicians/musicians.ts
  api/docs/schemas/profil/profil.ts
  api/docs/schemas/profil/userGroup/leaveGroup.ts
  api/log/logger.ts
  api/server/server.ts
  api/types/schema.ts
  index.ts
  package-lock.json
  package.json
Labels: enhancement

#126 User groups also return membership and instruments
  api/controllers/profil/profil.ts
  api/docs/openApiDoc.ts
  api/docs/schemas/profil/profil.ts
  api/types/schema.ts
Labels: enhancement

#127 Lite_admin cannot kick another lite_admin
  api/controllers/groups/kick.ts
  api/db/reset.ts
Labels: bug
